#!/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

SPAWN_FCGI="/usr/bin/spawn-fcgi"
DAEMON="/usr/sbin/fcgiwrap"
NAME="fcgiwrap"
DESC="FastCGI wrapper"

PIDFILE="/var/run/$NAME.pid"

test -x $SPAWN_FCGI || exit 0
test -x $DAEMON || exit 0

# FCGI_APP Variables
FCGI_CHILDREN="1"
FCGI_SOCKET="/var/run/fcgiwrap/$NAME.socket"
FCGI_USER="nginx"
FCGI_GROUP="nginx"
# Socket owner/group (will default to FCGI_USER/FCGI_GROUP if not defined)
FCGI_SOCKET_OWNER="nginx"
FCGI_SOCKET_GROUP="nginx"

DAEMON_OPTS="-f"        # By default we redirect STDERR output from executed
                        # CGI through FastCGI, to disable this behaviour set
                        # DAEMON_OPTS to an empty value in the default's file
exec $SPAWN_FCGI -s $FCGI_SOCKET  $ARGS -- $DAEMON $DAEMON_OPTS
